Repository AY2324S2-CS2113-W14-3/tp, pull requests merged in 2024-04, with the labels that each got.

#84 Add Help Command & Modification to View Command
  src/main/java/seedu/duke/FAP.java
  src/main/java/seedu/duke/command/HelpCommand.java
  src/main/java/seedu/duke/command/InvalidCommand.java
  src/main/java/seedu/duke/command/ViewCommand.java
  src/main/java/seedu/duke/modules/ModuleList.java
  src/main/java/seedu/duke/parser/CommandMetadata.java
  src/main/java/seedu/duke/parser/HelpCommandMetadata.java
  src/main/java/seedu/duke/parser/Parser.java
  src/main/java/seedu/duke/ui/Ui.java
  src/test/java/seedu/duke/FAPTest.java
  src/test/java/seedu/duke/ui/UiTest.java
  text-ui-test/EXPECTED.TXT
Labels: priority.High

#85 Support Equivalent Modules
  src/main/java/seedu/duke/enums/CEGModules.java
  src/main/java/seedu/duke/modules/ModuleList.java
  src/main/java/seedu/duke/ui/Ui.java
Labels: type.Enhancement, priority.Medium

#87 remove and graduate user guide
  docs/UserGuide.md
Labels: priority.High

#89 Update UserGuide with add command
  docs/UserGuide.md
Labels: priority.High

#101 Update UG and fix bugs for desiredgpa command
  docs/UserGuide.md
  src/main/java/seedu/duke/modules/Module.java
  src/main/java/seedu/duke/modules/ModuleList.java
  src/main/java/seedu/duke/ui/Ui.java
Labels: priority.High

#103 Refactor FAP and Storage to improve code quality
  src/main/java/seedu/duke/FAP.java
  src/main/java/seedu/duke/storage/Storage.java
Labels: type.Task, priority.Medium

#105 Fix unable to use coursecode starting with 4 alphabets
  src/main/java/seedu/duke/parser/CommandMetadata.java
  src/main/java/seedu/duke/ui/Ui.java
  src/test/java/seedu/duke/FAPTest.java
  src/test/java/seedu/duke/ui/UiTest.java
  text-ui-test/EXPECTED.TXT
Labels: type.Bug, priority.High

#150 Add S grade in Storage Class
  src/main/java/seedu/duke/storage/Storage.java
Labels: type.Bug, priority.High, severity.Medium

#151 Address database read bug in Storage class
  src/main/java/seedu/duke/storage/Storage.java
Labels: type.Bug, priority.High, severity.High

#152 Add JavaDocs for Storage and FAP Class
  src/main/java/seedu/duke/FAP.java
  src/main/java/seedu/duke/storage/Storage.java
Labels: type.Task, priority.Medium

#155 Add skeleton for PPP
  docs/team/dextboy.md
Labels: type.Task, priority.Medium

#162 Instructions for Manual Testing in DG
  docs/DeveloperGuide.md
  docs/team/jensonjenkins.md
Labels: type.Task, priority.High

#163 Class diagram addition
  docs/diagrams/ModuleList.png
  docs/diagrams/ModuleList.puml
Labels: type.Task, priority.High

#165 `Parser` and `User` DG Design & Implementation update
  docs/DeveloperGuide.md
  docs/diagrams/Parser.puml
  docs/diagrams/ParserClassDiagram.png
  docs/diagrams/ParserSequenceDiagram.png
  docs/diagrams/ParserSequenceDiagram.puml
Labels: priority.High

#164 Add Architecture Diagram and misc changes
  docs/DeveloperGuide.md
  docs/diagrams/Architecture.png
  docs/diagrams/Architecture.puml
  docs/diagrams/FAP.png
  docs/diagrams/FAP.puml
  docs/diagrams/Storage.puml
  docs/team/dextboy.md
Labels: type.Task, priority.High

#166 Documentation for 'Saving Modules to File' Functionality
  docs/DeveloperGuide.md
  docs/diagrams/Architecture.png
  docs/diagrams/Architecture.puml
  docs/diagrams/StorageSequenceDiagram.png
  docs/diagrams/StorageSequenceDiagram.puml
Labels: type.Task, priority.High

#169 Add Sequence diagram
  docs/DeveloperGuide.md
  docs/diagrams/AddCommand.png
  docs/diagrams/AddCommand.puml
Labels: type.Task, priority.High

#170 Update parser DG and diagrams
  docs/DeveloperGuide.md
  docs/diagrams/ArchitectureSequenceDiagram.png
  docs/diagrams/Parser.puml
  docs/diagrams/ParserClassDiagram.png
  docs/diagrams/ParserSequenceDiagram.png
  docs/diagrams/ParserSequenceDiagram.puml
Labels: type.Task, priority.High

#171 Developer Guide Storage improvement
  docs/DeveloperGuide.md
  docs/diagrams/Architecture.png
  docs/diagrams/Architecture.puml
  docs/diagrams/Storage.png
Labels: type.Task, priority.High

#176 DG Update
  docs/DeveloperGuide.md
Labels: type.Task, priority.High

#179 Deliverables update
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/duke/command/DesiredGpaCommand.java
  src/main/java/seedu/duke/command/GradeCommand.java
  src/main/java/seedu/duke/command/ViewGpaCommand.java
  src/main/java/seedu/duke/modules/ModuleList.java
Labels: type.Task, priority.High

#183 Include contributions to PPP
  docs/team/dextboy.md
Labels: type.Task, priority.Medium

#184 Include proper formatting for PPP
  docs/team/dextboy.md
Labels: type.Task, priority.High

#197 Update PPP for thaw and dexter
  docs/team/dextboy.md
  docs/team/thawtunzan.md
Labels: type.Task, priority.Medium
