Repository AY2324S2-CS2113-W14-3/tp, pull requests merged in 2024-03, with the labels that each got.

#43 Implement continuous command processing loop with error handling
  src/main/java/seedu/duke/FAP.java
  src/main/java/seedu/duke/command/ByeCommand.java
  src/main/java/seedu/duke/parser/Parser.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: priority.High

#44 Implement Initial Skeleton for 'init' Command
  src/main/java/seedu/duke/command/InitCommand.java
  src/main/java/seedu/duke/parser/Parser.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: priority.Medium

#48 Enhance Stability and Debugging in Main Function
  build.gradle
  src/main/java/seedu/duke/FAP.java
Labels: priority.High

#64 Update developer guide with FAP class details and UML diagram
  docs/DeveloperGuide.md
  docs/diagrams/FAP.png
  docs/diagrams/FAP.puml
  src/main/java/seedu/duke/exceptions/GpaNullException.java
Labels: priority.High

#67 Add More JUnit test and further revamp Parser to facilitate the Json
  src/main/java/seedu/duke/FAP.java
  src/main/java/seedu/duke/command/AddCommand.java
  src/main/java/seedu/duke/modules/Module.java
  src/main/java/seedu/duke/modules/ModuleList.java
  src/main/java/seedu/duke/parser/Parser.java
  src/test/java/seedu/duke/command/RemoveCommandTest.java
  src/test/java/seedu/duke/modules/ModuleListTest.java
Labels: priority.High

#71 Add unit tests for FAP initialization and error handling
  src/test/java/seedu/duke/FAPTest.java
Labels: priority.High

#76 Implement Storage Package for Module Data Persistence
  .gitignore
  src/main/java/seedu/duke/FAP.java
  src/main/java/seedu/duke/modules/Module.java
  src/main/java/seedu/duke/modules/ModuleList.java
  src/main/java/seedu/duke/parser/CommandMetadata.java
  src/main/java/seedu/duke/storage/Storage.java
Labels: priority.High

#78 Update method reference and modify .gitignore
  .gitignore
  src/main/java/seedu/duke/storage/Storage.java
Labels: type.Bug, severity.High

#79 Add and Integrate User class into FAP
  src/main/java/seedu/duke/FAP.java
  src/main/java/seedu/duke/command/InitCommand.java
  src/main/java/seedu/duke/command/ViewCommand.java
  src/main/java/seedu/duke/exceptions/UserException.java
  src/main/java/seedu/duke/modules/Module.java
  src/main/java/seedu/duke/modules/ModuleList.java
  src/main/java/seedu/duke/parser/CommandMetadata.java
  src/main/java/seedu/duke/parser/InitCommandMetadata.java
  src/main/java/seedu/duke/ui/Ui.java
  src/main/java/seedu/duke/user/User.java
  src/test/java/seedu/duke/FAPTest.java
  src/test/java/seedu/duke/parser/ParserTest.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: priority.Medium

#80 Enhance Storage Class to Include User Data and Extend Testing
  .gitignore
  docs/DeveloperGuide.md
  docs/diagrams/Storage.png
  docs/diagrams/Storage.puml
  src/main/java/seedu/duke/FAP.java
  src/main/java/seedu/duke/command/ByeCommand.java
  src/main/java/seedu/duke/exceptions/StorageException.java
  src/main/java/seedu/duke/modules/ModuleList.java
  src/main/java/seedu/duke/storage/Storage.java
  src/main/java/seedu/duke/ui/Ui.java
  src/test/java/seedu/duke/ExceptionHandleTest.java
  src/test/java/seedu/duke/FAPTest.java
  src/test/java/seedu/duke/storage/StorageTest.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: type.Epic, priority.High
